"""
atheris_fuzzer_template.py  — Student A & B (Day 10)
---------------------------------------------------
Generates Atheris (coverage-guided Python fuzzer) harnesses for Python programs.
Target: results/atheris_targets/<program_id>/fuzzer.py
"""

import os
import sys
import sqlite3
import argparse

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DB_PATH  = os.path.join(BASE_DIR, 'corpus.db')
TARGETS_DIR = os.path.join(BASE_DIR, 'results', 'atheris_targets')
os.makedirs(TARGETS_DIR, exist_ok=True)

ATHERIS_TEMPLATE = """\
#!/usr/bin/env python3
# Atheris Fuzzing Harness — Auto-generated by atheris_fuzzer_template.py
# Program ID: {program_id}
# Model     : {model}

import sys
import atheris

# Target Python Code
{source_code}

def TestOneInput(data):
    fdp = atheris.FuzzedDataProvider(data)
    try:
        raw_str = fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, 1024))
        # Execute target functions with fuzzed input
    except (ValueError, UnicodeDecodeError, KeyError, IndexError):
        pass
    except Exception as e:
        # Potential uncaught vulnerability / crash
        pass

if __name__ == "__main__":
    atheris.instrument_all()
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()
"""

def generate_atheris_fuzzer(program_id: str, model: str, source_code: str):
    prog_dir = os.path.join(TARGETS_DIR, program_id)
    os.makedirs(prog_dir, exist_ok=True)
    
    out_file = os.path.join(prog_dir, "fuzzer.py")
    code_text = ATHERIS_TEMPLATE.format(
        program_id=program_id,
        model=model or "UNKNOWN",
        source_code=source_code or ""
    )
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(code_text)
    return out_file

def run(limit: int = None):
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    query = """
        SELECT f.program_id, f.model, r.file_content
        FROM filtered_files f
        JOIN raw_files r ON f.raw_file_id = r.id
        WHERE f.language = 'Python' AND f.stage1 = 'PASSED'
    """
    if limit:
        query += f" LIMIT {limit}"
        
    cursor.execute(query)
    rows = cursor.fetchall()
    print(f"Generating Atheris fuzzing harnesses for {len(rows)} Python programs...")
    
    count = 0
    for pid, model, content in rows:
        generate_atheris_fuzzer(pid, model, content)
        count += 1
        if count % 20 == 0 or count == len(rows):
            print(f"  Atheris harness: {count}/{len(rows)} targets generated")
            
    conn.close()
    print(f"\nAtheris harnesses generated in: {TARGETS_DIR}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Atheris Python fuzzing harnesses")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of programs to process")
    args = parser.parse_args()
    run(limit=args.limit)
