import sqlite3
import time
import os
from github import Github
from dotenv import load_dotenv

load_dotenv()
g = Github(os.getenv('GITHUB_TOKEN'))

KEYWORDS = ['Generated by GitHub Copilot', 'Generated by ChatGPT', 'Written with ChatGPT', 'Generated by GPT-4', 'Generated by Gemini', 'Generated by DeepSeek']
LANGUAGES = ['C', 'Python']
KEYWORD_TO_TOOL = {'Generated by GitHub Copilot': 'copilot', 'Generated by ChatGPT': 'chatgpt', 'Written with ChatGPT': 'chatgpt', 'Generated by GPT-4': 'gpt4', 'Generated by Gemini': 'gemini', 'Generated by DeepSeek': 'deepseek'}

def collect_query(keyword, language, conn):
    cursor = conn.cursor()
    try:
        results = g.search_code(f'"{keyword}" language:{language}')
        count = 0
        for item in results:
            if count >= 1000: break
            try:
                content = item.decoded_content.decode('utf-8', errors='replace')
                cursor.execute('''INSERT OR IGNORE INTO raw_files (repo_name, file_path, commit_sha, star_count, language, raw_url, search_keyword, ai_tool, file_content) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)''', 
                               (item.repository.full_name, item.path, item.sha, item.repository.stargazers_count, language, item.download_url, keyword, KEYWORD_TO_TOOL[keyword], content))
                conn.commit()
                count += 1
                time.sleep(1)
            except Exception as e:
                time.sleep(2)
                continue
        print(f' Saved {count} files for: {keyword} [{language}]')
    except Exception as e:
        time.sleep(60)
    time.sleep(10)

if __name__ == '__main__':
    conn = sqlite3.connect('corpus.db')
    for lang in LANGUAGES:
        for keyword in KEYWORDS:
            print(f'Searching: "{keyword}" in {lang}...')
            collect_query(keyword, lang, conn)
    conn.close()