"""
collect_c_targeted.py
---------------------
Targeted GitHub collector specifically for C language files with AI attribution.
"""

import os
import sys
import time
import sqlite3
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
DB_PATH = os.path.join(BASE_DIR, 'corpus.db')

C_QUERIES = [
    ('copilot', 'generated by copilot language:C'),
    ('copilot', 'co-authored-by: github-copilot language:C'),
    ('copilot', 'github copilot language:C'),
    ('chatgpt', 'generated by chatgpt language:C'),
    ('chatgpt', 'chatgpt language:C'),
    ('gpt4', 'generated by gpt-4 language:C'),
    ('gpt4', 'gpt-4 language:C'),
    ('deepseek', 'generated by deepseek language:C'),
    ('deepseek', 'deepseek language:C'),
    ('gemini', 'generated by gemini language:C'),
    ('gemini', 'gemini language:C'),
    ('claude', 'generated by claude language:C'),
    ('claude', 'claude language:C'),
    ('tabnine', 'tabnine language:C'),
]

SEARCH_MIN_INTERVAL = 3.0
CONTENT_WORKERS = 10
last_search_call = [0.0]

session = requests.Session()
adapter = HTTPAdapter(pool_connections=15, pool_maxsize=15, max_retries=Retry(total=2, backoff_factor=0.5))
session.mount('https://', adapter)
session.mount('http://', adapter)

def fetch_file_content(item, ai_tool, query, headers):
    try:
        repo_name = item.get('repository', {}).get('full_name', '')
        file_path = item.get('path', '')
        html_url = item.get('html_url', '')
        if not repo_name or not file_path or not html_url:
            return None

        raw_url = (html_url
                   .replace('github.com', 'raw.githubusercontent.com')
                   .replace('/blob/', '/'))

        resp = session.get(raw_url, headers=headers, timeout=8)
        if resp.status_code != 200:
            return None
        content = resp.text
        if not content or len(content.strip().encode('utf-8')) < 100:
            return None
        if content.strip().lower().startswith('<!doctype') or content.strip().lower().startswith('<html'):
            return None

        return (repo_name, file_path, 'C', query, ai_tool, content)
    except Exception:
        return None

def collect_c():
    token = os.getenv('GITHUB_TOKEN') or os.getenv('GITHUB_PAT') or ''
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'C-Security-Research-Harvester'
    }
    
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    init_c = cursor.execute("SELECT count(*) FROM raw_files WHERE language='C'").fetchone()[0]
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Starting Targeted C Collection. Current C files: {init_c}")
    
    total_added = 0
    for ai_tool, query in C_QUERIES:
        print(f"\nSearching: '{query}' (tool={ai_tool})")
        for page in range(1, 6):
            elapsed = time.time() - last_search_call[0]
            if elapsed < SEARCH_MIN_INTERVAL:
                time.sleep(SEARCH_MIN_INTERVAL - elapsed)
                
            url = f"https://api.github.com/search/code?q={query}&per_page=100&page={page}"
            try:
                resp = session.get(url, headers=headers, timeout=15)
                last_search_call[0] = time.time()
                
                if resp.status_code in (403, 429):
                    reset = int(resp.headers.get('X-RateLimit-Reset', time.time() + 60))
                    wait = max(reset - int(time.time()) + 2, 5)
                    print(f"  [Rate limit] sleeping {wait}s...")
                    time.sleep(wait)
                    continue
                    
                if resp.status_code != 200:
                    print(f"  HTTP {resp.status_code}: {resp.text[:150]}")
                    break
                    
                data = resp.json()
                items = data.get('items', [])
                if not items:
                    break
                    
                print(f"  p{page}: got {len(items)} search items. Fetching contents...")
                
                added_in_page = 0
                with ThreadPoolExecutor(max_workers=CONTENT_WORKERS) as ex:
                    futures = [ex.submit(fetch_file_content, it, ai_tool, query, headers) for it in items]
                    for f in as_completed(futures):
                        res = f.result()
                        if res:
                            repo_name, file_path, lang, q, tool, content = res
                            try:
                                cursor.execute('''
                                    INSERT INTO raw_files (repo_name, file_path, language, search_keyword, ai_tool, file_content, keyword_in_comment)
                                    VALUES (?, ?, ?, ?, ?, ?, 1)
                                ''', (repo_name, file_path, lang, q, tool, content))
                                conn.commit()
                                added_in_page += 1
                                total_added += 1
                            except sqlite3.IntegrityError:
                                pass
                print(f"  p{page}: stored {added_in_page} new C files (total new: {total_added})")
            except Exception as e:
                print(f"  Query error: {e}")
                break
                
    final_c = cursor.execute("SELECT count(*) FROM raw_files WHERE language='C'").fetchone()[0]
    conn.close()
    print(f"\nTargeted C collection finished! Total new files added: {total_added}. New C total: {final_c}")

if __name__ == '__main__':
    collect_c()
