"""
generate_asan_harness.py  — Student A, Day 5
---------------------------------------------
Reads CBMC SAT counterexample records from formal_results, then generates a
minimal C harness (main() function) that:

  1. Declares the variables named in the counterexample assignment.
  2. Calls the analysis target function with those values.
  3. Compiles cleanly with:
       gcc -fsanitize=address,undefined -g -O0 -o harness harness.c target.c

Usage
-----
  # Dry-run: print harness to stdout without touching the DB or filesystem
  python generate_asan_harness.py --dry-run

  # Normal run: generate harnesses for all SAT entries in formal_results
  python generate_asan_harness.py

  # Limit to N programs
  python generate_asan_harness.py --limit 10

Output
------
  results/asan_harnesses/<program_id>/harness.c
"""

import argparse
import json
import os
import sqlite3
import sys
import re

BASE_DIR    = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DB_PATH     = os.path.join(BASE_DIR, 'corpus.db')
HARNESS_DIR = os.path.join(BASE_DIR, 'results', 'asan_harnesses')
CWE_PROP    = os.path.join(BASE_DIR, 'scripts', 'cwe_to_property.json')
ASAN_MAP    = os.path.join(BASE_DIR, 'scripts', 'asan_to_cwe.json')

# ---------------------------------------------------------------------------
# Jinja2 template for the harness (inline — no external file needed)
# ---------------------------------------------------------------------------
HARNESS_TEMPLATE = """\
/* ASAN/UBSan harness — auto-generated by generate_asan_harness.py
 * Program ID  : {{ program_id }}
 * CBMC result : {{ cbmc_result }}
 * Violated    : {{ violated_property }}
 * Source file : {{ file_path }}
 *
 * Compile:
 *   gcc -fsanitize=address,undefined -g -O0 \\
 *       -o harness harness.c <source_file.c>
 * Run:
 *   ./harness
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Forward-declare the target function.
 * Replace this declaration with the actual signature from the source file. */
extern int __attribute__((weak)) target_function(void);

/* ------------------------------------------------------------------
 * Counterexample variable assignments from CBMC
 * ------------------------------------------------------------------ */
{% for var in variables %}
static {{ var.type }} {{ var.name }} = {{ var.value }};
{% endfor %}

int main(void) {
    fprintf(stderr, "[harness] program_id={{ program_id }}\\n");
    fprintf(stderr, "[harness] violated={{ violated_property }}\\n");

{% if variables %}
    /* Exercise the vulnerable path using CBMC's witness values */
{% for var in variables %}
    (void){{ var.name }};
{% endfor %}
{% else %}
    /* No counterexample variables available — call target directly */
{% endif %}

    if (target_function) {
        int ret = target_function();
        fprintf(stderr, "[harness] target returned %d\\n", ret);
    } else {
        fprintf(stderr, "[harness] target_function symbol not found\\n");
    }

    return 0;
}
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_jinja2_or_fallback():
    """Try to load Jinja2; fall back to a simple string-replace renderer."""
    try:
        from jinja2 import Environment
        env = Environment()
        tmpl = env.from_string(HARNESS_TEMPLATE)
        def render(ctx):
            return tmpl.render(**ctx)
        return render
    except ImportError:
        # Fallback: manual substitution (no Jinja2 installed)
        def render_fallback(ctx):
            out = HARNESS_TEMPLATE
            out = out.replace("{{ program_id }}", str(ctx.get("program_id", "")))
            out = out.replace("{{ cbmc_result }}", str(ctx.get("cbmc_result", "")))
            out = out.replace("{{ violated_property }}", str(ctx.get("violated_property", "")))
            out = out.replace("{{ file_path }}", str(ctx.get("file_path", "")))
            # Render variable list
            var_decls = "\n".join(
                f"static int {v['name']} = 0;  /* type unknown */"
                for v in ctx.get("variables", [])
            )
            out = re.sub(r'\{%.*?%\}', '', out, flags=re.DOTALL)
            out = out.replace("{% for var in variables %}\nstatic {{ var.type }} {{ var.name }} = {{ var.value }};\n{% endfor %}", var_decls)
            return out
        return render_fallback


def parse_cbmc_variables(counterexample_json: str) -> list:
    """Parse a JSON counterexample assignment into a list of variable dicts.

    Each dict has: name, type, value.
    Returns [] on any parse error.
    """
    if not counterexample_json:
        return []
    try:
        data = json.loads(counterexample_json)
        if isinstance(data, list):
            result = []
            for item in data:
                result.append({
                    "name": item.get("name", "var"),
                    "type": item.get("type", "int"),
                    "value": item.get("value", "0"),
                })
            return result
        return []
    except (json.JSONDecodeError, TypeError):
        return []


def generate_harness(program_id: str, cbmc_result: str, violated_property: str,
                     file_path: str, counterexample_json: str, render_fn,
                     dry_run: bool = False) -> str:
    """Generate and optionally write a harness file. Returns the harness text."""
    variables = parse_cbmc_variables(counterexample_json)

    ctx = {
        "program_id":        program_id,
        "cbmc_result":       cbmc_result,
        "violated_property": violated_property or "unknown",
        "file_path":         file_path or "unknown",
        "variables":         variables,
    }
    harness_text = render_fn(ctx)

    if not dry_run:
        out_dir  = os.path.join(HARNESS_DIR, program_id)
        out_path = os.path.join(out_dir, "harness.c")
        os.makedirs(out_dir, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(harness_text)
        print(f"  Wrote: {out_path}")

    return harness_text


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run(limit: int = None, dry_run: bool = False):
    render_fn = load_jinja2_or_fallback()

    conn = sqlite3.connect(DB_PATH)
    c    = conn.cursor()

    query = """
        SELECT fr.program_id, fr.cbmc_result, fr.property_type,
               fr.counterexample_json, ff.file_path
        FROM formal_results fr
        LEFT JOIN filtered_files ff ON fr.program_id = ff.program_id
        WHERE fr.cbmc_result = 'SAT'
        ORDER BY fr.program_id
    """
    if limit:
        query += f" LIMIT {limit}"

    rows = c.execute(query).fetchall()
    conn.close()

    if not rows:
        print("No SAT entries in formal_results yet.")
        print("Run CBMC on Linux, then run parse_cbmc_xml.py, then re-run this script.")
        if dry_run:
            # Dry-run demonstration with synthetic data
            print("\n[DRY-RUN] Generating example harness with synthetic data...\n")
            example_text = generate_harness(
                program_id="prog_000001",
                cbmc_result="SAT",
                violated_property="array-bounds-upper",
                file_path="results/static_raw/example.c",
                counterexample_json='[{"name":"idx","type":"int","value":"128"},{"name":"buf_len","type":"int","value":"64"}]',
                render_fn=render_fn,
                dry_run=True,
            )
            print(example_text)
        return

    print(f"Generating ASAN harnesses for {len(rows)} SAT entries...")
    if dry_run:
        print("[DRY-RUN mode — no files will be written]\n")

    if not dry_run:
        os.makedirs(HARNESS_DIR, exist_ok=True)

    for program_id, cbmc_result, property_type, ce_json, file_path in rows:
        generate_harness(
            program_id=program_id,
            cbmc_result=cbmc_result,
            violated_property=property_type,
            file_path=file_path,
            counterexample_json=ce_json,
            render_fn=render_fn,
            dry_run=dry_run,
        )

    if not dry_run:
        print(f"\nDone. Harnesses written to: {HARNESS_DIR}")
        print("Next step: on Linux, compile each harness with:")
        print("  gcc -fsanitize=address,undefined -g -O0 -o harness harness.c <source.c>")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate ASAN/UBSan harnesses from CBMC SAT counterexamples"
    )
    parser.add_argument("--limit", type=int, default=None,
                        help="Process only this many SAT entries")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print harness to stdout; do not write files")
    args = parser.parse_args()
    run(limit=args.limit, dry_run=args.dry_run)
