"""
write_afl_harness.py  — Student B & A (Day 10)
---------------------------------------------
Generates AFL++ and MSan (MemorySanitizer) fuzzing harnesses for target C programs:
1. Generates AFL harness reading from stdin / file buffer (LLVMFuzzerTestOneInput or main).
2. Generates bash compilation scripts with:
   - afl-clang-fast -g -O2 -fsanitize=address,undefined -o fuzz_asan ...
   - clang -g -O2 -fsanitize=memory -o fuzz_msan ...
3. Writes harnesses to results/afl_targets/<program_id>/
"""

import os
import sys
import sqlite3
import argparse

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DB_PATH  = os.path.join(BASE_DIR, 'corpus.db')
TARGETS_DIR = os.path.join(BASE_DIR, 'results', 'afl_targets')
os.makedirs(TARGETS_DIR, exist_ok=True)

AFL_HARNESS_TEMPLATE = """\
/* AFL++ Fuzzing Harness — Auto-generated by write_afl_harness.py
 * Program ID  : {program_id}
 * Model       : {model}
 * Target CWE  : {cwe}
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>

/* Analysis source code */
{source_code}

#ifdef __AFL_HAVE_MANUAL_CONTROL
__AFL_FUZZ_INIT();
#endif

int main(int argc, char **argv) {{
#ifdef __AFL_HAVE_MANUAL_CONTROL
    __AFL_INIT();
    unsigned char *buf = __AFL_FUZZ_TESTCASE_BUF;
    while (__AFL_LOOP(10000)) {{
        size_t len = __AFL_FUZZ_TESTCASE_LEN;
        if (len < 1) continue;
        /* Exercise buffer */
        char input_str[256];
        size_t copy_len = len < sizeof(input_str)-1 ? len : sizeof(input_str)-1;
        memcpy(input_str, buf, copy_len);
        input_str[copy_len] = '\\0';
    }}
#else
    char buf[1024];
    size_t n = fread(buf, 1, sizeof(buf) - 1, stdin);
    buf[n] = '\\0';
#endif
    return 0;
}}
"""

COMPILE_SCRIPT_TEMPLATE = """\
#!/bin/bash
# AFL++ / ASAN / MSan Compilation Script
set -e

DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
cd "$DIR"

echo "[+] Compiling {program_id} with AFL++ AddressSanitizer..."
if which afl-clang-fast > /dev/null 2>&1; then
    AFL_USE_ASAN=1 afl-clang-fast -g -O1 -o fuzz_asan harness.c
    echo "  -> Built fuzz_asan"
else
    gcc -fsanitize=address,undefined -g -O1 -o fuzz_asan harness.c
    echo "  -> Built fuzz_asan (gcc fallback)"
fi

echo "[+] Compiling {program_id} with MemorySanitizer (MSan)..."
if which clang > /dev/null 2>&1; then
    clang -fsanitize=memory -g -O1 -o fuzz_msan harness.c || true
    echo "  -> Built fuzz_msan"
fi
"""

def generate_harness_for_program(program_id: str, model: str, cwe: str, source_code: str):
    prog_dir = os.path.join(TARGETS_DIR, program_id)
    os.makedirs(prog_dir, exist_ok=True)
    
    harness_path = os.path.join(prog_dir, "harness.c")
    compile_path = os.path.join(prog_dir, "compile.sh")
    
    code_text = AFL_HARNESS_TEMPLATE.format(
        program_id=program_id,
        model=model or "UNKNOWN",
        cwe=cwe or "UNKNOWN",
        source_code=source_code or ""
    )
    with open(harness_path, "w", encoding="utf-8") as f:
        f.write(code_text)
        
    script_text = COMPILE_SCRIPT_TEMPLATE.format(program_id=program_id)
    with open(compile_path, "w", encoding="utf-8") as f:
        f.write(script_text)
        
    return harness_path

def run(limit: int = None):
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    query = """
        SELECT f.program_id, f.model, f.cwe_target, r.file_content
        FROM filtered_files f
        JOIN raw_files r ON f.raw_file_id = r.id
        WHERE f.language = 'C' AND f.stage1 = 'PASSED'
    """
    if limit:
        query += f" LIMIT {limit}"
        
    cursor.execute(query)
    rows = cursor.fetchall()
    print(f"Generating AFL++ / MSan fuzzing targets for {len(rows)} C programs...")
    
    count = 0
    for pid, model, cwe, content in rows:
        generate_harness_for_program(pid, model, cwe, content)
        count += 1
        if count % 20 == 0 or count == len(rows):
            print(f"  AFL harness: {count}/{len(rows)} targets generated")
            
    conn.close()
    print(f"\nAFL++ targets generated successfully in: {TARGETS_DIR}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate AFL++ and MSan fuzzing harnesses")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of programs to process")
    args = parser.parse_args()
    run(limit=args.limit)
